/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,ts}"],
  theme: {

    // extend: {
    colors: {
      'primary-black': 'var(--color-primary-black)',
      'primary-white': 'var(--color-primary-white)',
      'primary-red': 'var(--color-primary-red)',
      'secondary-red-100': 'var(--color-secondary-red-100)',
      'secondary-red-200': 'var(--color-secondary-red-200)',
      'secondary-red-300': 'var(--color-secondary-red-300)',
      'secondary-blue-100': 'var(--color-secondary-blue-100)',
      'secondary-blue-200': 'var(--color-secondary-blue-200)',
      'secondary-blue-300': 'var(--color-secondary-blue-300)',
      'secondary-green': 'var(--color-secondary-green)',
      'neutral-grey-10': 'var(--color-neutral-grey-10)',
      'neutral-grey-20': 'var(--color-neutral-grey-20)',
      'neutral-grey-25': 'var(--color-neutral-grey-25)',
      'neutral-grey-50': 'var(--color-neutral-grey-50)',
      'neutral-grey-100': 'var(--color-neutral-grey-100)',
      'neutral-grey-150': 'var(--color-neutral-grey-150)',
      'neutral-grey-200': 'var(--color-neutral-grey-200)',
      'neutral-grey-250': 'var(--color-neutral-grey-250)',
      'neutral-grey-300T40': 'var(--color-neutral-grey-300T40)',
      'neutral-grey-300T70': 'var(--color-neutral-grey-300T70)',
      'neutral-grey-350': 'var(--color-neutral-grey-350)',
      'neutral-grey-400': 'var(--color-neutral-grey-400)',
      'neutral-grey-450': 'var(--color-neutral-grey-450)',
      'neutral-grey-500': 'var(--color-neutral-grey-500)',
      'neutral-grey-550': 'var(--color-neutral-grey-550)',
      'neutral-grey-600T60': 'var(--color-neutral-grey-600T60)',
      'neutral-grey-600': 'var(--color-neutral-grey-600)',
      'neutral-grey-650': 'var(--color-neutral-grey-650)',
      'neutral-grey-700': 'var(--color-neutral-grey-700)',
      'neutral-grey-750': 'var(--color-neutral-grey-750)',
      'neutral-grey-800': 'var(--color-neutral-grey-800)',
      'neutral-grey-850': 'var(--color-neutral-grey-850)',
      'neutral-grey-900': 'var(--color-neutral-grey-900)',
      'transparent-white-15': 'var(--color-transparent-white-15)',
      'transparent-white-20': 'var(--color-transparent-white-20)',
      'transparent-white-30': 'var(--color-transparent-white-30)',
      'transparent-white-35': 'var(--color-transparent-white-35)',
      'transparent-white-50': 'var(--color-transparent-white-50)',
      'transparent-white-70': 'var(--color-transparent-white-70)',
      'transparent-black-30': 'var(--color-transparent-black-30)',
      'transparent-black-60': 'var(--color-transparent-black-60)',
      'transparent-black-90': 'var(--color-transparent-black-90)',
    },
    fontFamily: {
      display: ['var(--font-display)', 'sans-serif'],
      body: ['var(--font-body)', 'sans-serif'],
    },
    fontSize: {
      'xs': 'var(--font-size-xs)',
      'sm': 'var(--font-size-sm)',
      'base': 'var(--font-size-base)',
      'lg': 'var(--font-size-lg)',
      'xl': 'var(--font-size-xl)',
      '2xl': 'var(--font-size-2xl)',
      '3xl': 'var(--font-size-3xl)',
      '4xl': 'var(--font-size-4xl)',
      '5xl': 'var(--font-size-5xl)',
      '6xl': 'var(--font-size-6xl)',
      '7xl': 'var(--font-size-7xl)',

    }
    // },
  },
  plugins: [],
};